# cluster specific values
cluster:
  # specify cluster name
  name: qa-hardcoded-0

# specify cloud credential secret name, do not need to be provided if using custom driver
cloudCredentialSecretName: qa-do
